-- Your SQL goes here
CREATE TABLE personal_information (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    name_ext VARCHAR,
    middle_name VARCHAR,
    birth_date VARCHAR NOT NULL,
    birth_place VARCHAR NOT NULL,
    sex VARCHAR NOT NULL,
    civil_status VARCHAR NOT NULL,
    height VARCHAR,
    weight VARCHAR,
    bloodtype VARCHAR,
    gsis VARCHAR,
    pagibig VARCHAR,
    philhealth VARCHAR,
    sss VARCHAR,
    tin VARCHAR,
    agency_employee VARCHAR,
    citizenship VARCHAR,
    ra_lot_no VARCHAR,
    ra_street VARCHAR,
    ra_subdivision VARCHAR,
    ra_barangay VARCHAR,
    ra_city VARCHAR,
    ra_province VARCHAR,
    ra_zip_code VARCHAR,
    pa_lot_no VARCHAR,
    pa_street VARCHAR,
    pa_subdivision VARCHAR,
    pa_barangay VARCHAR,
    pa_city VARCHAR,
    pa_province VARCHAR,
    pa_zip_code VARCHAR,
    mobile_number VARCHAR,
    telephone_number VARCHAR,
    email_address VARCHAR,
   
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);