// @generated automatically by Diesel CLI.

diesel::table! {
    personal_information (id) {
        id -> Int4,
        first_name -> Varchar,
        last_name -> Varchar,
        name_ext -> Nullable<Varchar>,
        middle_name -> Nullable<Varchar>,
        birth_date -> Varchar,
        birth_place -> Varchar,
        sex -> Varchar,
        civil_status -> Varchar,
        height -> Nullable<Varchar>,
        weight -> Nullable<Varchar>,
        bloodtype -> Nullable<Varchar>,
        gsis -> Nullable<Varchar>,
        pagibig -> Nullable<Varchar>,
        philhealth -> Nullable<Varchar>,
        sss -> Nullable<Varchar>,
        tin -> Nullable<Varchar>,
        agency_employee -> Nullable<Varchar>,
        citizenship -> Nullable<Varchar>,
        ra_lot_no -> Nullable<Varchar>,
        ra_street -> Nullable<Varchar>,
        ra_subdivision -> Nullable<Varchar>,
        ra_barangay -> Nullable<Varchar>,
        ra_city -> Nullable<Varchar>,
        ra_province -> Nullable<Varchar>,
        ra_zip_code -> Nullable<Varchar>,
        pa_lot_no -> Nullable<Varchar>,
        pa_street -> Nullable<Varchar>,
        pa_subdivision -> Nullable<Varchar>,
        pa_barangay -> Nullable<Varchar>,
        pa_city -> Nullable<Varchar>,
        pa_province -> Nullable<Varchar>,
        pa_zip_code -> Nullable<Varchar>,
        mobile_number -> Nullable<Varchar>,
        telephone_number -> Nullable<Varchar>,
        email_address -> Nullable<Varchar>,
        created_at -> Timestamp,
    }
}
